[package]
name = "Impulse-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3.0"
bcrypt = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
